language: python
python:
  - 3.5
  - 3.6

branches:
  only:
  - master

install:
  - pip install -r requirements.txt
  # required for optional dworp.plot
  - pip install matplotlib
  - pip install -r test_requirements.txt
before_script:
  - flake8 dworp
script:
  - nosetests --with-coverage
after_success:
  - coveralls
